.\" This man page for createstructure
.TH createstructure "1" "2021-07-17" "createstructure 09.01.01" "User Commands"
.SH NAME
createstructure
.SH SYNOPSIS
.B createstructure - launch application
.br
.B createstructure [--help | -h] - Help
.br
.B createstructure [--login | -l] - Login with help
.br
.B createstructure [--login | -l] [--username | -u] [--token | -t] - Login without any input request
.SH DESCRIPTION
Repo containing the clientside for Ubuntu/Debian
.SH AUTHORS
Castellani Davide (@DavideC03): owner